package eu.bbmri_eric.quality.server.dataquality.controller;

import eu.bbmri_eric.quality.server.common.dto.FilterDTO;
import eu.bbmri_eric.quality.server.dataquality.ReportPdfService;
import eu.bbmri_eric.quality.server.dataquality.ReportService;
import eu.bbmri_eric.quality.server.dataquality.dto.ReportCreateRequest;
import eu.bbmri_eric.quality.server.dataquality.dto.ReportDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.hateoas.EntityModel;
import org.springframework.hateoas.PagedModel;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/** REST controller for managing reports. */
@RestController
@RequestMapping("/api/v1")
@Tag(name = "Reports", description = "API for managing data quality reports")
class ReportController {

  private final ReportService reportService;
  private final ReportPdfService reportPdfService;
  private final ReportLinkBuilder linkBuilder;

  public ReportController(
      ReportService reportService,
      ReportPdfService reportPdfService,
      ReportLinkBuilder linkBuilder) {
    this.reportService = reportService;
    this.reportPdfService = reportPdfService;
    this.linkBuilder = linkBuilder;
  }

  @PostMapping("/agents/{agentId}/reports")
  @Operation(
      summary = "Create a new report",
      description = "Creates a new data quality report for an agent")
  public ResponseEntity<EntityModel<ReportDTO>> create(
      @PathVariable String agentId, @Valid @RequestBody ReportCreateRequest createRequest) {
    ReportDTO createdReport = reportService.create(agentId, createRequest);
    EntityModel<ReportDTO> reportModel = linkBuilder.toModel(createdReport);
    return ResponseEntity.status(HttpStatus.CREATED).body(reportModel);
  }

  @GetMapping("/reports/{id}")
  @Operation(
      summary = "Get report by ID",
      description = "Retrieves a specific report by its unique identifier")
  public ResponseEntity<EntityModel<ReportDTO>> findById(@PathVariable String id) {
    ReportDTO report = reportService.findById(id);
    EntityModel<ReportDTO> reportModel = linkBuilder.toModel(report);
    return ResponseEntity.ok(reportModel);
  }

  @GetMapping("/agents/{agentId}/reports")
  @Operation(
      summary = "Get reports by agent ID",
      description = "Retrieves reports generated by a specific agent with pagination")
  public ResponseEntity<PagedModel<EntityModel<ReportDTO>>> findByAgentId(
      @PathVariable String agentId, @Valid @ParameterObject FilterDTO filter) {
    return ResponseEntity.ok(
        linkBuilder.toPagedModelForAgent(
            reportService.findByAgentId(agentId, filter), agentId, filter));
  }

  @GetMapping("/reports")
  @Operation(
      summary = "Get all reports",
      description = "Retrieves all reports in the system with pagination")
  public ResponseEntity<PagedModel<EntityModel<ReportDTO>>> findAll(
      @Valid @ParameterObject FilterDTO filter) {
    // TODO: Add support for filtering
    return ResponseEntity.ok(linkBuilder.toPagedModel(reportService.findAll(filter), filter));
  }

  @GetMapping("/reports/{id}/summary")
  @Operation(
      summary = "Get report summary as PDF",
      description = "Generates a PDF summary for a specific report")
  public ResponseEntity<byte[]> generateSummary(
      @PathVariable String id, @RequestParam(defaultValue = "pdf") String format) {
    byte[] pdf = reportPdfService.generateReportSummary(id);
    return ResponseEntity.ok()
        .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"report-summary.pdf\"")
        .contentType(MediaType.APPLICATION_PDF)
        .body(pdf);
  }
}
