version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      all-actions:
        patterns:
          - "*"

  - package-ecosystem: "maven"
    directories:
      - "/agent/backend"
      - "/server/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
    labels:
      - "dependencies"
      - "java"
    groups:
      all-java:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/agent/frontend"
      - "/server/frontend"
      - "/docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      all-js:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/agent"
      - "/server"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
    labels:
      - "dependencies"
      - "docker"
    groups:
      all-docker:
        patterns:
          - "*"