spring.datasource.url=jdbc:sqlite:dev_agent.db?busy_timeout=30000
spring.flyway.locations=classpath:db/migration/,db/dev/migration
logging.level.eu.bbmri_eric.quality.agent=debug
logging.level.ca.uhn.fhir=info
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.leak-detection-threshold=30000
