spring.datasource.url=jdbc:postgresql://server-db:5432/quality_server
spring.datasource.username=${DB_USERNAME:quality}
spring.datasource.password=${DB_PASSWORD:quality}
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.leak-detection-threshold=60000
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.show-sql=false
