spring.flyway.locations=classpath:db/migration/,db/dev/migration
logging.level.eu.bbmri_eric.quality.server=debug
app.crypto.key-path=/Users/radovan.tomasik/Repositories/data-quality-framework/signing.p12