name: CI/CD Pipeline
on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Check Code Format (Agent)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('modules/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - working-directory: modules/backend
        run: mvn --quiet clean com.spotify.fmt:fmt-maven-plugin:check

  lint-server:
    name: Check Code Format (Server)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-server-${{ hashFiles('server/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-server-
      - working-directory: server/backend
        run: mvn --quiet clean com.spotify.fmt:fmt-maven-plugin:check

  test:
    name: Run Tests (Agent)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('modules/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - working-directory: modules/backend
        run: mvn --quiet test

  test-server:
    name: Run Tests (Server)
    runs-on: ubuntu-latest
    needs: lint-server
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-server-${{ hashFiles('server/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-server-
      - working-directory: server/backend
        run: mvn --quiet test

  migration:
    name: Test DB Migration (Agent)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - run: docker compose up -d quality-agent
        name: Spin up latest stable image

      - uses: docker/build-push-action@v6
        name: Build new image
        with:
          context: .
          tags: ghcr.io/bbmri-cz/data-quality-agent:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - run: docker compose down
        name: Down the container

      - run: docker compose up -d quality-agent
        name: Spin up new image

      - name: Check container health
        run: |
          for i in {1..20}; do
          STATUS=$(docker inspect --format='{{.State.Health.Status}}' quality-agent)
          echo "Health status: $STATUS"
          if [ "$STATUS" == "healthy" ]; then
          echo "Container is healthy"
          exit 0
          fi
          sleep 3
          done
          echo "Container is not healthy"
          docker logs quality-agent
          exit 1

  migration-server:
    name: Test DB Migration (Server)
    runs-on: ubuntu-latest
    needs: lint-server
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - run: docker compose up -d quality-server || exit 0
        name: Spin up latest stable image

      - uses: docker/build-push-action@v6
        name: Build new image
        with:
          context: ./server
          tags: ghcr.io/bbmri-cz/data-quality-server:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - run: docker compose down
        name: Down the container

      - run: docker compose up -d quality-server
        name: Spin up new image

      - name: Check container health
        run: |
          for i in {1..20}; do
          STATUS=$(docker inspect --format='{{.State.Health.Status}}' quality-server)
          echo "Health status: $STATUS"
          if [ "$STATUS" == "healthy" ]; then
          echo "Container is healthy"
          exit 0
          fi
          sleep 3
          done
          echo "Container is not healthy"
          docker logs quality-server
          exit 1

  docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'docs/package-lock.json'

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Build documentation
        working-directory: docs
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build:
    name: Build Agent
    runs-on: ubuntu-latest
    needs:
      - test
      - migration
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('modules/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - working-directory: modules/backend
        run: mvn --quiet clean package -DskipTests

      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/data-quality-agent
          tags: |
            type=sha
            type=raw,value=${{ github.head_ref }},event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ARTIFACT_VERSION=${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/bbmri-cz/data-quality-agent:latest
          build-args: ARTIFACT_VERSION=${{ github.ref_name }}
          cache-from: type=gha
          outputs: type=docker,dest=/tmp/agent-image.tar

      - name: Upload agent image artifact
        uses: actions/upload-artifact@v4
        with:
          name: agent-image
          path: /tmp/agent-image.tar

  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    needs:
      - test-server
      - migration-server
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-server-${{ hashFiles('server/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-server-

      - working-directory: server/backend
        run: mvn --quiet clean package -DskipTests

      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/data-quality-server
          tags: |
            type=sha
            type=raw,value=${{ github.head_ref }},event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ARTIFACT_VERSION=${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: docker/build-push-action@v6
        with:
          context: ./server
          tags: ghcr.io/bbmri-cz/data-quality-server:latest
          build-args: ARTIFACT_VERSION=${{ github.ref_name }}
          cache-from: type=gha
          outputs: type=docker,dest=/tmp/server-image.tar

      - name: Upload server image artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-image
          path: /tmp/server-image.tar

  integration-test:
    name: System test
    runs-on: ubuntu-latest
    needs:
      - build
      - build-server
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download agent image artifact
        uses: actions/download-artifact@v4
        with:
          name: agent-image
          path: /tmp

      - name: Download server image artifact
        uses: actions/download-artifact@v4
        with:
          name: server-image
          path: /tmp

      - name: Load Docker images
        run: |
          docker load -i /tmp/agent-image.tar
          docker load -i /tmp/server-image.tar

      - name: Create integration docker-compose
        run: docker compose up -d

      - name: Check agent health
        run: |
          for i in {1..20}; do
          STATUS=$(docker inspect --format='{{.State.Health.Status}}' quality-agent)
          echo "Health status: $STATUS"
          if [ "$STATUS" == "healthy" ]; then
          echo "Container is healthy"
          exit 0
          fi
          sleep 3
          done
          echo "Container is not healthy"
          docker logs quality-server
          exit 1

      - name: Check server health
        run: |
          for i in {1..20}; do
          STATUS=$(docker inspect --format='{{.State.Health.Status}}' quality-server)
          echo "Health status: $STATUS"
          if [ "$STATUS" == "healthy" ]; then
          echo "Container is healthy"
          exit 0
          fi
          sleep 3
          done
          echo "Container is not healthy"
          docker logs quality-server
          exit 1